### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by dcherian** [NCAR/jupyter-forward#72]
Here's an error message I received

```
[I 2021-03-30 13:02:13.315 ServerApp] dask_labextension | extension was found and enabled by nbclassic. Consider moving the extension to Jupyter Server's extension paths.
[I 2021-03-30 13:02:13.315 ServerApp] dask_labextension | extension was successfully linked.
[I 2021-03-30 13:02:13.715 ServerApp] jupyter_server_proxy | extension was found and enabled by nbclassic. Consider moving the extension to Jupyter Server's extension paths.
[I 2021-03-30 13:02:13.715 ServerApp] jupyter_server_proxy | extension was successfully linked.
[I 2021-03-30 13:02:13.715 ServerApp] nbclassic | extension was successfully linked.
[I 2021-03-30 13:02:14.492 ServerApp] [nb_conda_kernels] enabled, 9 kernels found
[I 2021-03-30 13:02:14.581 ServerApp] The port 8888 is already in use, trying another port.
[I 2021-03-30 13:02:14.587 ServerApp] dask_labextension | extension was successfully loaded.
[I 2021-03-30 13:02:14.612 ServerApp] jupyter_server_proxy | extension was successfully loaded.
[I 2021-03-30 13:02:14.613 LabApp] JupyterLab extension loaded from /glade/u/home/dcherian/miniconda3/lib/python3.7/site-packages/jupyterlab
[I 2021-03-30 13:02:14.613 LabApp] JupyterLab application directory is /glade/work/dcherian/miniconda3/share/jupyter/lab
[I 2021-03-30 13:02:14.616 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-03-30 13:02:14.617 ServerApp] jupyterlab_code_formatter | extension was successfully loaded.
[I 2021-03-30 13:02:14.628 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-03-30 13:02:14.628 ServerApp] Serving notebooks from local directory: /glade/u/home/dcherian
[I 2021-03-30 13:02:14.628 ServerApp] Jupyter Server 1.4.1 is running at:
[I 2021-03-30 13:02:14.628 ServerApp] http://casper-login2:8889/lab
[I 2021-03-30 13:02:14.628 ServerApp]  or http://127.0.0.1:8889/lab
[I 2021-03-30 13:02:14.628 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

***********************************************************
*** Terminated the network connection to the remote end ***
***********************************************************

Traceback (most recent call last):
  File "/home/deepak/miniconda3/bin/jupyter-forward", line 11, in <module>
    load_entry_point('jupyter-forward', 'console_scripts', 'jupyter-forward')()
  File "/home/deepak/work/python/jupyter-forward/jupyter_forward/cli.py", line 97, in main
    typer.run(app())
  File "/home/deepak/miniconda3/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/deepak/miniconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/deepak/miniconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/deepak/miniconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/deepak/miniconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/deepak/miniconda3/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/deepak/work/python/jupyter-forward/jupyter_forward/cli.py", line 93, in start
    runner.start()
  File "/home/deepak/work/python/jupyter-forward/jupyter_forward/core.py", line 143, in start
    self.parsed_result = parse_stdout(stdout)
  File "/home/deepak/work/python/jupyter-forward/jupyter_forward/core.py", line 226, in parse_stdout
    hostname, port = result.netloc.split(':')
ValueError: not enough values to unpack (expected 2, got 1)
```

I tried a couple of minutes layer and then things worked. Maybe add a `try..except` block to print out more information that could be useful for debugging?

**Comment by andersy005** [comment]
Thank you, @dcherian! Did this error persist or did it end up going away?

**Comment by andersy005** [comment]
This has been addressed in https://github.com/NCAR/jupyter-forward/pull/77
